name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.2

    - name: Install dependencies
      run: go mod download

    - name: Format code
      run: |
        fmt_output=$(gofmt -l .)
        if [ -n "$fmt_output" ]; then
          echo "The following files are not formatted:"
          echo "$fmt_output"
          exit 1
        fi

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Build Docker image
      run: docker build -t fibonacci-web-service ./web-service
      # This is where we could push to a registry, sign the image, etc.